import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Listify",
  description:
    "Generated by create next appOrganize your tasks with ease and track your to-dos in a sleek, simple interface for maximum productivity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
